stages:
  ingest:
    cmd: python data_ingestion/jd_ingestion/serp_api/serpapi_ingest.py
    deps:
      - data_ingestion/jd_ingestion/serp_api/serpapi_ingest.py
      - data_ingestion/jd_ingestion/serp_api/serpapi_client.py   
      - data_ingestion/jd_ingestion/serp_api/priority_scheduler.py 
      - data/constants/jobs.csv
      - data/constants/locations.yaml
      - utils/paths.py 
      - utils
    params:
      - serpapi_ingestion
    outs:
      - data/raw/serpapi
    
  process_jd_raw_jsons:
    cmd: python data_ingestion\processors\process_data.py
    deps:
      - data_ingestion/processors/process_data.py
      - data/raw/serpapi  # Depends on the raw folder
      - utils/            # Depends on utils logic
    outs:
      - data/processed/