stages:
  ingest:
    cmd: python data_ingestion/jd_ingestion/serp_api/serpapi_ingest.py
    deps:
      - data_ingestion/jd_ingestion/serp_api/serpapi_ingest.py
      - data_ingestion/jd_ingestion/serp_api/serpapi_client.py   
      - data_ingestion/jd_ingestion/serp_api/priority_scheduler.py 
      - utils/paths.py 
      - utils
    params:
      - serpapi_ingestion
      - ingest.current_month
    outs:
      - data/raw/serpapi/${ingest.current_month}
    
  process_jd_raw_jsons:
    cmd: python data_ingestion\processors\process_data.py
    deps:
      - data_ingestion/processors/process_data.py
      - data/raw/serpapi/${ingest.current_month}  # Depends on the raw folder
      - utils/            # Depends on utils logic
    outs:
      - data/processed/serpapi/${ingest.current_month}.csv

  label_scraped_jobs:
    cmd: python src/label_jobs.py
    deps:
      - src/label_jobs.py
      - data/processed/serpapi/${ingest.current_month}.csv  # Triggers if any month folder or CSV changes
      - utils/
    outs:
      - data/final/serpapi/${ingest.current_month}.csv

  build_vector_store:
    cmd: python src/vector_db/ingest.py
    deps:
      - src/vector_db/ingest.py
      - src/vector_db/client.py 
      - src/vector_db/encoder.py
      - data/final/serpapi/${ingest.current_month}.csv
      - utils/
    params:
      - ingest.current_month
    outs:
    - data/final/serpapi/${ingest.current_month}.vector_done:
        cache: false #This output should NOT be cached, versioned, or restored by DVC “Because the actual output of the stage is a database side effect, which DVC cannot track. The sentinel file acts as a deterministic completion marker for the pipeline, while cache: false prevents DVC from falsely restoring state it cannot reproduce
