filenames:
  jobs_data: jobs.csv
  locations_data: locations.yaml

ingest:
  current_month: "2026-01"

ml_models:
  job_labeler:
    name: Job_Categorizer_Production
    version_alias: champion
  vector_encoding:
    batch_size: 16

serpapi_ingestion:
  max_api_calls: 2500
